package gui;

import syntax.connector;
import syntax.judulpage;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Acer
 */
public class update extends javax.swing.JFrame {
    private void reset(){
        txtidobt.setText(null);
        txtnamapas.setText(null);
        txtkeluhan.setText(null);
        txttgl.setText(null);
    }
    
    private void tabel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No ");
        model.addColumn("id_pasien ");
        model.addColumn("id_obat");        
        model.addColumn("nama");
        model.addColumn("keluhan");
        model.addColumn("tanggal");
    
        try{
            int no = 1;
            String sql = "SELECT * FROM pengobatan";
            java.sql.Connection conn = (Connection)connector.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++, res.getString(1),
                                                res.getString(2),
                                                res.getString(3),
                                                res.getString(4),
                                                res.getString(5)});
            }
            tabel.setModel(model);
            
        }catch(SQLException e){
            System.out.println("Eror : " + e.getMessage());
        }
    }
    /**
     * Creates new form up
     */
    public update() {
        initComponents();
        reset();
        tabel();
        judulpage u =new judulpage();
        judulupdate.setText(u.judulu());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txttgl = new javax.swing.JTextField();
        txtkeluhan = new javax.swing.JTextField();
        txtnamapas = new javax.swing.JTextField();
        txtidobt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        backbutton = new javax.swing.JButton();
        judulupdate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 414));
        jPanel2.setLayout(null);

        txttgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttglActionPerformed(evt);
            }
        });
        jPanel2.add(txttgl);
        txttgl.setBounds(250, 350, 220, 30);

        txtkeluhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkeluhanActionPerformed(evt);
            }
        });
        jPanel2.add(txtkeluhan);
        txtkeluhan.setBounds(250, 280, 220, 30);

        txtnamapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapasActionPerformed(evt);
            }
        });
        jPanel2.add(txtnamapas);
        txtnamapas.setBounds(250, 210, 220, 30);

        txtidobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidobtActionPerformed(evt);
            }
        });
        jPanel2.add(txtidobt);
        txtidobt.setBounds(250, 140, 220, 30);

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(300, 400, 120, 40);

        tabel = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tabel.getTableHeader().setReorderingAllowed(false);
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(520, 140, 540, 390);

        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(backbutton);
        backbutton.setBounds(10, 10, 110, 50);

        judulupdate.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        judulupdate.setForeground(new java.awt.Color(255, 255, 255));
        judulupdate.setText("jLabel13");
        jPanel2.add(judulupdate);
        judulupdate.setBounds(490, 20, 190, 29);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID OBAT");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 140, 110, 25);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NAMA PASIEN");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(110, 210, 140, 25);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KELUHAN");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(110, 280, 150, 25);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TANGGAL");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(110, 350, 110, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttglActionPerformed

    private void txtkeluhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkeluhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkeluhanActionPerformed

    private void txtnamapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapasActionPerformed

    private void txtidobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidobtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidobtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txtidobt.getText().isEmpty() && !txtnamapas.getText().isEmpty() && !txtkeluhan.getText().isEmpty() && !txttgl.getText().isEmpty()) {
        try{
            String sql = "UPDATE pengobatan SET id_obat='"
            +txtidobt.getText()+"',nama='"
            +txtnamapas.getText()+"',keluhan='"
            +txtkeluhan.getText()+"',tanggal='"
            +txttgl.getText()+"' WHERE id_pasien='"+tabel.getModel().getValueAt(tabel.getSelectedRow(), 1)+"'";
            java.sql.Connection conn = (Connection)connector.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Pasien berhasil diubah");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tabel();
        reset();
        } else {
        JOptionPane.showMessageDialog(null, "Input tidak boleh kosong ");
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
            int baris = tabel.rowAtPoint(evt.getPoint());
//            String nip = tabel.getValueAt(baris, 1).toString();
//            txtidpas.setText(nip);
        
            String nama = tabel.getValueAt(baris, 2).toString();
            txtidobt.setText(nama);
        
            String usia = tabel.getValueAt(baris, 3).toString();
            txtnamapas.setText(usia);
        
            String nohp = tabel.getValueAt(baris, 4).toString();
            txtkeluhan.setText(nohp);
        
            String jenjang = tabel.getValueAt(baris, 5).toString();
            txttgl.setText(jenjang);
        
    }//GEN-LAST:event_tabelMouseClicked

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        new menu(). show();
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulupdate;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtidobt;
    private javax.swing.JTextField txtkeluhan;
    private javax.swing.JTextField txtnamapas;
    private javax.swing.JTextField txttgl;
    // End of variables declaration//GEN-END:variables
}
